# Generated by Django 5.2.3 on 2025-07-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Введите цену курса в рублях",
                max_digits=10,
                verbose_name="Цена курса",
            ),
        ),
    ]
